version: '3.3'

services:

  spark-master:
    image: bde2020/spark-master:2.3.0-hadoop2.7
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    networks:
      - spark
    volumes:
      - spark-master:/spark/work

  spark-worker:
    image: bde2020/spark-worker:2.3.0-hadoop2.7
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    networks:
      - spark

networks:
  spark:
    attachable: true

volumes:
  spark-master:
